#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

from common import apply_config_to_env, get_arango_config, load_dotenv, sanitize_url

try:
    from arango import ArangoClient  # type: ignore
except Exception:  # pragma: no cover
    ArangoClient = None  # type: ignore


ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = ROOT / "docs" / "phase3-analytics-report.md"


@dataclass
class AnalyticsCounts:
    cycle_edges: int
    mule_edges: int
    mule_hubs_ge_50: int
    mule_distinct_devices: int
    undervalued_sales: int
    golden_records: int
    resolved_to_edges: int


def connect(cfg):
    if ArangoClient is None:  # pragma: no cover
        raise SystemExit("python-arango not installed. Install: pip install -r requirements.txt")
    client = ArangoClient(hosts=cfg.url)
    return client.db(cfg.database, username=cfg.username, password=cfg.password)


def compute_counts(db) -> AnalyticsCounts:
    # Circular trading (scenario tag)
    q_cycle = "RETURN LENGTH(FOR e IN transferredTo FILTER e.scenario == 'cycle' RETURN 1)"
    cycle_edges = int(list(db.aql.execute(q_cycle))[0])

    # Mule ring edges
    q_mule = "RETURN LENGTH(FOR e IN transferredTo FILTER e.scenario == 'mule' RETURN 1)"
    mule_edges = int(list(db.aql.execute(q_mule))[0])

    # Mule hubs (>=50 inbound mule transfers)
    q_hubs = """
FOR e IN transferredTo
  FILTER e.scenario == "mule"
  COLLECT hub = e._to WITH COUNT INTO n
  FILTER n >= 50
  RETURN 1
"""
    mule_hubs_ge_50 = int(len(list(db.aql.execute(q_hubs))))

    # Mule shared device count among mule sources
    q_devices = """
LET muleFrom = UNIQUE(
  FOR e IN transferredTo
    FILTER e.scenario == "mule"
    RETURN e._from
)
LET devices = UNIQUE(
  FOR a IN accessedFrom
    FILTER a._from IN muleFrom
    RETURN a._to
)
RETURN LENGTH(devices)
"""
    mule_distinct_devices = int(list(db.aql.execute(q_devices))[0])

    # Undervalued property sales
    q_undervalued = """
WITH RealProperty, RealEstateTransaction, registeredSale
RETURN LENGTH(
  FOR e IN registeredSale
    LET p = DOCUMENT(e._from)
    LET tx = DOCUMENT(e._to)
    FILTER p != null && tx != null
    FILTER tx.transactionValue <= p.circleRateValue
    RETURN 1
)
"""
    undervalued_sales = int(list(db.aql.execute(q_undervalued))[0])

    # ER outputs
    q_gr = "RETURN LENGTH(FOR g IN GoldenRecord RETURN 1)"
    golden_records = int(list(db.aql.execute(q_gr))[0])
    q_rt = "RETURN LENGTH(FOR e IN resolvedTo RETURN 1)"
    resolved_to_edges = int(list(db.aql.execute(q_rt))[0])

    return AnalyticsCounts(
        cycle_edges=cycle_edges,
        mule_edges=mule_edges,
        mule_hubs_ge_50=mule_hubs_ge_50,
        mule_distinct_devices=mule_distinct_devices,
        undervalued_sales=undervalued_sales,
        golden_records=golden_records,
        resolved_to_edges=resolved_to_edges,
    )


def write_report(*, cfg, counts: AnalyticsCounts) -> None:
    now = datetime.now(timezone.utc).isoformat()
    content = "\n".join(
        [
            "# Phase 3 analytics report",
            "",
            "This report is generated by `scripts/phase3_analytics.py`.",
            "",
            f"- **Generated at (UTC):** `{now}`",
            f"- **Mode:** `{cfg.mode}`",
            f"- **ArangoDB:** `{sanitize_url(cfg.url)}`",
            f"- **Database:** `{cfg.database}`",
            "",
            "## Pattern counts (demo scale)",
            "",
            f"- **Circular trading** (`transferredTo.scenario == \"cycle\"`) edges: **{counts.cycle_edges}**",
            f"- **Money mule ring** (`transferredTo.scenario == \"mule\"`) edges: **{counts.mule_edges}**",
            f"- **Mule hubs** (>= 50 inbound mule transfers): **{counts.mule_hubs_ge_50}**",
            f"- **Mule shared devices** (distinct `DigitalLocation` for mule sources): **{counts.mule_distinct_devices}**",
            f"- **Undervalued property sales** (`transactionValue <= circleRateValue`): **{counts.undervalued_sales}**",
            "",
            "## Entity Resolution (Phase 2 outputs present)",
            "",
            f"- `GoldenRecord` count: **{counts.golden_records}**",
            f"- `resolvedTo` count: **{counts.resolved_to_edges}**",
            "",
            "## Notes",
            "",
            "- Queries are intentionally bounded / aggregate-only for demo stability.",
            "- For deeper exploration, use Visualizer canvas actions on KnowledgeGraph.",
            "",
        ]
    )
    REPORT_PATH.write_text(content, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Phase 3: compute analytics summaries for core fraud patterns.")
    p.add_argument("--mode", choices=["LOCAL", "REMOTE"], default=None, help="Override MODE from .env")
    return p.parse_args()


def main() -> None:
    load_dotenv()
    args = parse_args()
    cfg = get_arango_config(forced_mode=args.mode)
    apply_config_to_env(cfg)

    if not cfg.url:
        raise SystemExit("ARANGO_URL is not set")

    # Never print secrets; sanitize URL.
    print(f"[phase3] analytics mode={cfg.mode} arango={sanitize_url(cfg.url)} db={cfg.database}")
    db = connect(cfg)

    counts = compute_counts(db)
    write_report(cfg=cfg, counts=counts)

    # Emit counts only (safe)
    out: Dict[str, Any] = {
        "cycle_edges": counts.cycle_edges,
        "mule_edges": counts.mule_edges,
        "mule_hubs_ge_50": counts.mule_hubs_ge_50,
        "mule_distinct_devices": counts.mule_distinct_devices,
        "undervalued_sales": counts.undervalued_sales,
        "golden_records": counts.golden_records,
        "resolved_to_edges": counts.resolved_to_edges,
        "report_path": str(REPORT_PATH),
    }
    print(out)


if __name__ == "__main__":
    sys.exit(main())

