#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Optional

from common import apply_config_to_env, get_arango_config, load_dotenv, sanitize_url, wait_for_http_ok


ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = ROOT / "docs" / "phase2-validation-report.md"


@dataclass
class StepResult:
    ok: bool
    detail: str = ""


def run(cmd: List[str], env: Optional[Dict[str, str]] = None) -> StepResult:
    try:
        subprocess.run(cmd, cwd=str(ROOT), check=True, env=env or os.environ.copy())
        return StepResult(True)
    except subprocess.CalledProcessError as e:
        return StepResult(False, f"command failed: {' '.join(cmd)} (exit {e.returncode})")


def run_pytest_integration() -> StepResult:
    return run(["pytest", "-q", "-m", "integration"])


def run_entity_resolution(mode: str) -> StepResult:
    return run(
        [
            sys.executable,
            "scripts/entity_resolution.py",
            "--mode",
            mode,
            "--ensure-overlap",
            "--overlap-count",
            "50",
        ]
    )


def write_report(remote: Dict, local: Dict) -> None:
    def section(title: str, data: Dict) -> str:
        if not data:
            return f"## {title}\n\n- **Status:** not run\n\n"
        lines = [f"## {title}", ""]
        lines.append(f"- **Status:** {'PASS' if data.get('ok') else 'FAIL'}")
        if data.get("mode"):
            lines.append(f"- **Mode:** {data['mode']}")
        if data.get("arango_url"):
            lines.append(f"- **ArangoDB:** `{data['arango_url']}`")
        if data.get("db"):
            lines.append(f"- **Database:** `{data['db']}`")
        lines.append("")
        for k in ["connectivity", "entity_resolution", "pytest_integration"]:
            if k in data:
                v = data[k]
                status = "PASS" if v.get("ok") else "FAIL"
                detail = v.get("detail", "")
                lines.append(f"- **{k}**: {status}" + (f" — {detail}" if detail else ""))
        lines.append("")
        return "\n".join(lines)

    content = "\n".join(
        [
            "# Phase 2 validation report",
            "",
            "This report is generated by `scripts/test_phase2.py`.",
            "",
            section("REMOTE (Managed)", remote),
            section("LOCAL (Docker)", local),
        ]
    )
    REPORT_PATH.write_text(content, encoding="utf-8")


def run_mode(mode: str) -> Dict:
    cfg = get_arango_config(forced_mode=mode)
    apply_config_to_env(cfg)

    result: Dict = {
        "mode": cfg.mode,
        "arango_url": sanitize_url(cfg.url),
        "db": cfg.database,
        "ok": True,
    }

    # Connectivity (no secrets printed)
    try:
        wait_for_http_ok(cfg.url, timeout_s=60)
        result["connectivity"] = asdict(StepResult(True))
    except Exception as e:
        result["connectivity"] = asdict(StepResult(False, str(e)))
        result["ok"] = False
        return result

    # ER run
    er = run_entity_resolution(mode)
    result["entity_resolution"] = asdict(er)
    if not er.ok:
        result["ok"] = False
        return result

    # Integration tests (GoldenRecord/resolvedTo assertions)
    pti = run_pytest_integration()
    result["pytest_integration"] = asdict(pti)
    if not pti.ok:
        result["ok"] = False
        return result

    return result


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Run Phase 2 tests for REMOTE then LOCAL.")
    p.add_argument("--local-only", action="store_true", help="Only run LOCAL")
    p.add_argument("--remote-only", action="store_true", help="Only run REMOTE")
    return p.parse_args()


def main() -> None:
    load_dotenv()
    args = parse_args()

    remote: Dict = {}
    local: Dict = {}

    if not args.local_only:
        remote = run_mode("REMOTE")
    if not args.remote_only:
        local = run_mode("LOCAL")

    write_report(remote=remote, local=local)

    ok = True
    if remote and not remote.get("ok"):
        ok = False
    if local and not local.get("ok"):
        ok = False

    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()

